baseURL: 'https://jtsmith.me'
languageCode: 'en-us'
title: "JT Smith's Blog"
publishDir: "docs"
theme: "PaperMod"

# home-info mode
homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

socialIcons:
    - name: twitter
        url: "https://twitter.com/"
    - name: linkedin
        url: "https://stackoverflow.com"
    - name: github
        url: "https://github.com/"